MA-11933-3 fix compile error when upgrade to android-p-preview-2
There's several compile errors for CactusPlayer,FSLOta,librecovery_ui_imx and lib_omx*,
not build them temporary.

Compile errors are like below:
1)vendor/nxp/fsl_imx_omx/CactusPlayer/src/com/freescale/cactusplayer/HdmiApplication.java:343: error: cannot find symbol
                 Settings.Global.WIFI_ON), false, mSettingsObserver, UserHandle.USER_ALL);
                                                                               ^
  symbol:   variable USER_ALL
  location: class UserHandle

2)vendor/nxp-opensource/fsl_imx_demo/FSLOta/src/com/fsl/android/ota/OTAServerManager.java:77: error: package UpdateEngine does not exist
                        if (status == UpdateEngine.UpdateStatusConstants.DOWNLOADING) {

3)device/fsl/common/recovery/recovery_ui.cpp:85:24: error: virtual function 'GetMenuItems' has a different return type
('const char *const *') than the function it overrides (which has return type 'const std::vector<std::string> &'
(aka 'const vector<basic_string<char, char_traits<char>, allocator<char> > > &'))
    const char* const* GetMenuItems() { return ITEMS; }
          ~~~~~~~~~~~~ ^

4)target SharedLib: lib_omx_amr_dec_v2_arm11_elinux
prebuilts/clang/host/linux-x86/clang-r328903/bin/ld.lld: error: found local symbol
'_bss_end__' in global part of symbol table in file out/target/product/evk_8mq/obj/lib/lib_wb_amr_dec_arm9_elinux.so

prebuilts/clang/host/linux-x86/clang-r328903/bin/ld.lld: error: found local symbol
'__bss_start__' in global part of symbol table in file out/target/product/evk_8mq/obj/lib/lib_wb_amr_dec_arm9_elinux.so

Change-Id: I8ddcb43e86ab7689ac29bc6505435883d0430110
Signed-off-by: Jessie Hao <juan.hao@nxp.com>
Reviewed-on: http://androidsource.ap.freescale.net/project/4726
Reviewed-by: guoyin.chen <guoyin.chen@nxp.com>