MA-16453 Fix build error in android-r-preview-1.
1.Meet below error log when compile kernel:
scripts/kconfig/conf  --syncconfig Kconfig
scripts/Kconfig.include:35: compiler 'clang' not found

Switch to clang-r353983c to avoid this issue.

2.Meet beloe error log:
FAILED:
external/mesa3d/Android.mk:40: error: external/mesa3d must be in
PRODUCT_SOONG_NAMESPACES.

PRODUCT_SOONG_NAMESPACES add external/mesa3d to avoid this issue.

3.Meet beloe error log:
device/fsl/common/recovery/recovery_ui.cpp:23:10: fatal error: 'common.h'
file not found

Change-Id: I2ba3039210e3280d32426740b938b3db78045abc
Signed-off-by: Jessie Hao <juan.hao@nxp.com>
Reviewed-on: http://androidsource.ap.freescale.net/project/11434
Reviewed-by: guoyin.chen <guoyin.chen@nxp.com>
Reviewed-on: http://androidsource.ap.freescale.net/project/11988