MA-18223-1 Cannot access /sys/class/thermal/thermal_zoneX/temp on 8mp
miss CONFIG_IMX8MM_THERMAL to tmu_get_temp, after adding this,
"binding zone cpu-thermal with cdev", failed to register cool device,
so add CONFIG_DEVICE_THERMAL, and need to remove CONFIG_DEVFREQ_THERMAL
for that "d.lld: error: duplicate symbol: devfreq_cooling_register"

Change-Id: I49d440cd5cd910f30ee69b3bef46fc7d04dd758a
Signed-off-by: Dandan Sun <dandan.sun@nxp.com>
Reviewed-on: http://androidsource.ap.freescale.net/project/14017
Reviewed-by: zhang sanshan <sanshan.zhang@nxp.com>