MA-10166 Build error as init.i.MX8MQ.rc not found for evk_8mq
Use init.imx8mq.rc to replace init.i.MX8MQ.rc
Fix the build error as below:
error: 'device/fsl/evk_8mq/init.i.MX8MQ.rc',
needed by 'out/target/product/evk_8mq/root/init.freescale.i.MX8MQ.rc',
missing and no known rule to make it

Change-Id: I39f99f8bcf155f3de13d1260c3f730ddb2e8108f
Signed-off-by: guoyin.chen <guoyin.chen@nxp.com>
Reviewed-on: http://androidsource.ap.freescale.net/project/2784
Reviewed-by: Xuegang Liu <xuegang.liu@nxp.com>
Reviewed-by: zhang sanshan <sanshan.zhang@nxp.com>